### ISSUE TITLE
Access denied while pulling images

### ISSUE THREAD

**Issue by tarunwadhwa13** [udacity/CNAND_nd064_Building_a_Metrics_Dashboard_Starter_Files#1]
For the manifests in app folder, image referred is ghcr.io/thejaysmith/mybackend:v1 
I am able to pull myfrontend but for mybackend and mytrial, it says denied

```
docker pull ghcr.io/thejaysmith/mytrial:v1
Error response from daemon: Get https://ghcr.io/v2/thejaysmith/mytrial/manifests/v1: denied
```

Url - 
https://github.com/udacity/CNAND_nd064_Building_a_Metrics_Dashboard_Starter_Files/blob/master/manifests/app/backend.yaml#L17

**Comment by kushshukla24** [comment]
I am also facing the same issue. Any solution?

**Comment by hungapp** [comment]
Same issue! The image for the trial-app is failing to be pulled either. I don't think there's any solution other than the instructor fixing the images URLs.

**Comment by hungapp** [comment]
@TheJaySmith could you take a look at this issue, please?

**Comment by TheJaySmith** [comment]
It's a typo on my end. It should say "trial" not "mytrial". Thanks for pointing it out. I fixed it
